### PR TITLE
Merge +itemClassificationScheme.csv into the standard

### PR DESCRIPTION
**Pull request by ColinMaudry**
See https://github.com/open-contracting/standard/issues/1157

### CODE REVIEW

**Comment by ColinMaudry** [comment]
@jpmckinney As soon as you validate the wording in the README I do the other extensions mentioned in https://github.com/open-contracting/standard/issues/1157

**Review by jpmckinney — APPROVED** [review]

**Comment by jpmckinney** [comment]
I created and pushed a 1.1 branch, so merging.

**Comment by jpmckinney** [comment]
What I ultimately chose to do was make the default branch 1.1 (instead of master), create a new 1.2 branch with these commits, and delete the master branch. Requests to the `master` branch will return the default branch (1.1) (GitHub returns the default branch for non-existent branches). Once 1.2 is released, we can change the default branch to 1.2, so that `master` returns that branch instead. In the meantime, we won't disrupt any users expecting the 1.1 version on `master`.

**Comment by ColinMaudry** [comment]
@jpmckinney What about https://github.com/open-contracting-extensions/ocds_legalBasis_extension/pull/6#issuecomment-778516885 ?

**Comment by ColinMaudry** [comment]
This redirection doesn't seem to work:

https://raw.githubusercontent.com/open-contracting-extensions/ocds_legalBasis_extension/bla/extension.json would redirect to https://raw.githubusercontent.com/open-contracting-extensions/ocds_legalBasis_extension/1.1/extension.json, but it returns a 404.

**Comment by jpmckinney** [comment]
Ah, I think maybe the branch needs to have existed once? https://raw.githubusercontent.com/open-contracting-extensions/ocds_legalBasis_extension/master/extension.json redirects, but the branch doesn't exist.

**Pull request merged**
