### PR TITLE
Added itemClassificationScheme codelist

### PR DESCRIPTION
**Pull request by ColinMaudry**

### CODE REVIEW

**Comment by jpmckinney** [comment]
@ColinMaudry Looks like the new codelist file is missing :)

**Comment by ColinMaudry** [comment]
Related to https://github.com/open-contracting-extensions/european-union/issues/69

**Comment by ColinMaudry** [comment]
Do I need to add something to release-schema? :confused:

**Comment by ColinMaudry** [comment]
I guess not, everything seems to be handled in `Classification`.

**Comment by ColinMaudry** [comment]
I just wonder whether we should document the values of these codelist somewhere. We do a codelist of codelists... but where are the codes? :laughing:

**Comment by jpmckinney** [comment]
> I just wonder whether we should document the values of these codelist somewhere. We do a codelist of codelists... but where are the codes? 😆

The idea is that people can refer to the Source URL to find more information. For the EU codelists, the codes are clear from the guidance.

**Pull request merged**
